behaviors:
  JumperAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 328
      learning_rate: 0.0003
      buffer_size: 10240 
      beta: 0.005
      epsilon: 0.2
      lambd: 0.93
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.93
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 50000